name: 📦 Create CodeDeploy revision
description: 📦 Create CodeDeploy revision
inputs:
  name:
    description: '(Required) Name of the application'
    required: true
  version:
    description: '(Required) Version of the application'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        echo "version: ${{ inputs.version }}
        os: linux
        files:
          - source: /application.jar
            destination: /home/ec2-user/${{ inputs.name }}
            overwrite: true
          - source: /application.yml
            destination: /home/ec2-user/${{ inputs.name }}
            overwrite: true
        hooks:
          ApplicationStop:
            - location: scripts/01-application-stop.sh
              timeout: 300
              runas: root
          BeforeInstall:
            - location: scripts/02-before-install.sh
              timeout: 300
              runas: root
          AfterInstall:
            - location: scripts/03-after-install.sh
              timeout: 300
              runas: root
          ApplicationStart:
            - location: scripts/04-application-start.sh
              timeout: 300
              runas: root
          ValidateService:
            - location: scripts/05-validate-service.sh
              timeout: 300
              runas: root
        " >> appspec.yml
        echo "toto"
        ls -la
        echo "tata"
        cat appspec.yml
      shell: bash
