name: CI TEST
on:
  push:
env:
  APPLICATION_NAME: toto
jobs:
  job-a:
    name: Job A
    runs-on: ubuntu-22.04
    steps:
      - run: echo ${{ env.APPLICATION_NAME }}

  job-b:
    name: Job B
    needs: [job-a]
    runs-on: ubuntu-22.04
    steps:
      - run: echo ${{ env.APPLICATION_NAME }}
      - uses: ./.github/actions/debug@master
