name: CI TEST
on:
  push:
    inputs:
      environment:
        type: string
        default: dev
jobs:
  job-a:
    name: Job A
    runs-on: ubuntu-22.04
    steps:
      - run: echo ${{ env.TOTO }}
      - run: echo $TOTO
      - run: echo "TOTO=toto" >> $GITHUB_ENV
      - run: echo ${{ env.TOTO }}
      - run: echo $TOTO
