name: CI TEST
on:
  push:
env:
  APPLICATION_NAME: toto
jobs:
  job-a:
    name: Job A
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/debug
      - uses: ./.github/actions/debug
        with:
          application-name: tata
