name: CI TEST
on:
  push:
    inputs:
      environment:
        type: string
        default: dev
jobs:
  job-a:
    name: Job A
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ inputs.environment }}
      - run: echo ${{ github.event.inputs.environment }}
      - uses: ./.github/actions/debug
