name: CI TEST
on:
  push:
jobs:
  workflow:
    name: workflow
    runs-on: ubuntu-22.04
    steps:
      - name: 🔓 Generate token for Velco GitHub Agent
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.CI_GITHUB_APPS_VELCO_GITHUB_AGENT_APP_ID }}
          private_key: ${{ secrets.CI_GITHUB_APPS_VELCO_GITHUB_AGENT_PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: VelcoTech/github-workflows
          token: ${{ steps.generate-token.outputs.token }}
          path: github-workflows
      - run: ls -la
      - run: ls -laR github-workflows
      - uses: ./.github/actions/create-codedeploy-revision
        with:
          name: my-app
          version: 1.0.0
      - run: ls -la
