name: CI TEST
on:
  push:
env:
  foo: foo
jobs:
  job-a:
    name: Job A
    runs-on: ubuntu-22.04
    steps:
      - run: echo ${{ env.foo }}
      - run: echo 'foo=bar' >> $GITHUB_ENV
      - run: echo ${{ env.foo }}


  job-b:
    name: Job B
    needs: [job-a]
    runs-on: ubuntu-22.04
    steps:
      - run: echo ${{ env.foo }}