name: CI TEST
on:
  push:
env:
  foo: foo
jobs:
  job-a:
    name: Job A
    runs-on: ubuntu-22.04
    steps:
      - run: echo $foo
      - run: echo 'foo=bar' >> $GITHUB_ENV


  job-b:
    name: Job B
    runs-on: ubuntu-22.04
    steps:
      - run: echo $foo