name: WORKFLOW B
on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: dev
jobs:
  reusable:
    name: reusable
    runs-on: ubuntu-22.04
    steps:
      - run: echo ${{ inputs.environment }}
      - run: echo ${{ github.event.inputs.environment }}
      - uses: actions/checkout@v4
      - uses: ./.github/actions/debug
