name: CI TEST
on:
  push:
jobs:
  workflow:
    name: workflow
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/create-codedeploy-revision
        with:
          name: my-app
          version: 1.0.0
