name: CI TEST
on:
  push:
jobs:
  workflow:
    name: workflow
    runs-on: ubuntu-22.04
    steps:
      - run: echo ${{ startsWith('Hello', 'He') }}
      - run: echo ${{ startsWith('Hello', 'he') }}
      - run: echo ${{ startsWith('Hello', ['He', 'he']) }}
